# Generated by Django 2.0.4 on 2018-04-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('NumSemestres', models.PositiveSmallIntegerField(null=True)),
                ('NumCreditosGrad', models.PositiveSmallIntegerField(null=True)),
                ('Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Facultad')),
            ],
        ),
    ]
