# Generated by Django 2.0.4 on 2018-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaacademico',
            name='Codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
