# Generated by Django 2.0.4 on 2018-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_programaacademico_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='Nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='programaacademico',
            name='Codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
