# Generated by Django 2.0.4 on 2018-04-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_programaacademico_escuela'),
        ('usuarios', '0002_auto_20180418_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.ProgramaAcademico'),
        ),
    ]
