# Generated by Django 2.0.4 on 2018-04-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_programaacademico_escuela'),
        ('usuarios', '0003_user_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programas.Facultad'),
        ),
    ]
