# Generated by Django 2.0.4 on 2018-04-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Creditos', models.PositiveSmallIntegerField()),
                ('HorasDeClaseMagistral', models.PositiveSmallIntegerField(null=True)),
                ('NumHorasEstudio', models.PositiveSmallIntegerField(null=True)),
                ('TipoDeCurso', models.CharField(choices=[('Asignatura básica', 'Asignatura básica'), ('Asignatura Profesional', 'Asignatura Profesional'), ('Electiva Complementaria', 'Electiva Complementaria'), ('Electiva Profesional', 'Electiva Profesional')], default='Asignatura básica', max_length=50)),
                ('Validable', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('Habilitable', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('NumSemestreUbic', models.PositiveSmallIntegerField(null=True)),
                ('AsigPrerrequisitos', models.ManyToManyField(blank=True, to='cursos.Curso')),
                ('Programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.ProgramaAcademico')),
            ],
        ),
    ]
