# Generated by Django 2.0.4 on 2018-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20180418_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
