# Generated by Django 2.0.4 on 2018-05-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20180419_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadesDeFormacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Competencia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IndicadoresDeLogro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habilidad', models.CharField(max_length=15)),
                ('Contenido', models.CharField(max_length=100)),
                ('Contexto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verbo', models.CharField(max_length=15)),
                ('Contenidos', models.CharField(max_length=100)),
                ('Contexto', models.CharField(max_length=100)),
                ('Proposito', models.CharField(max_length=100)),
                ('Competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Competencias')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='Habilitable',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='SI', max_length=2),
        ),
        migrations.AddField(
            model_name='indicadoresdelogro',
            name='RA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.ResultadoDeAprendizaje'),
        ),
        migrations.AddField(
            model_name='actividadesdeformacion',
            name='RA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.ResultadoDeAprendizaje'),
        ),
        migrations.AddField(
            model_name='actividadesdeevaluacion',
            name='IL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.IndicadoresDeLogro'),
        ),
    ]
