# Generated by Django 2.0.4 on 2018-06-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20180524_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencias',
            name='Curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
        migrations.AlterField(
            model_name='actividadesdeevaluacion',
            name='IL',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.IndicadoresDeLogro'),
        ),
        migrations.AlterField(
            model_name='actividadesdeformacion',
            name='RA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.ResultadoDeAprendizaje'),
        ),
        migrations.AlterField(
            model_name='indicadoresdelogro',
            name='RA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.ResultadoDeAprendizaje'),
        ),
        migrations.AlterField(
            model_name='resultadodeaprendizaje',
            name='Competencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.Competencias'),
        ),
    ]
